dtmilano/AndroidViewClient

src/com/dtmilano/android/culebron.py

--scale  option stopped working after the latest update. It doesn't take any value other than the default '1'

Fixed the scaling option

---

src/com/dtmilano/android/viewclient.py

The --compressed option is used for uiautomator dump by default. There
was no option to switch it of. As output of 'compressed' and
'uncompressed' dump is different, backward compatibility was broken.
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>

viewclient: added switch for --compressed option

---

src/com/dtmilano/android/common.py

Needed to do and extra check if platform.system() returns the value of 'Java' and check and the OS environment variable to see if we are in a Windows environment.  The os.getenv() will default to none if it not set.

platform.system() could return a value of Java causing the adb look up to fail on a windows system.

---

src/com/dtmilano/android/adb/adbclient.py

I was using this method as follows:
```python
_,_,width, height = vc.device.getRestrictedScreen()
w_midpoint = int(int(width)/2)
h_midpoint = int(int(height)/2)
vc.device.drag((w_midpoint,h_midpoint),(w_midpoint - 200, h_midpoint), 100)
```
I would like to make this function public again, so that I can continue to use it.  It is not used internally anywhere and is dead code otherwise.

Re-Expose method to allow clients to grab screensize

---

src/com/dtmilano/android/adb/adbclient.py

Very sorry that I made a mistake!
The sdk version is actual 17(I mistake as 18).
API levle >= 18 (4.3) supports the param 'duration'.
Very sorry!

A mistake I made!

---

src/com/dtmilano/android/adb/adbclient.py
tests/com/dtmilano/android/adb/adbclienttests.py

All adbclienttests should now run on most devices (any one with a calculator)

AVC: Fix adbclient.type to check type and fix package tests

---

src/com/dtmilano/android/viewclient.py

If UiAutomatorHelper is being used, and a View is clicked, find the UiObject first, and click it; but fallback to co-ords if this fails.

AVC: Try clicking as UiObject w/ UIAH, then fallback to coords

---

src/com/dtmilano/android/common.py

Code was intended to search an absolute path (/opt/blah) but the first separation character isn't automatically added by os.join

Fix absolute adb path in Mac and Linux

---

src/com/dtmilano/android/viewclient.py

Increasing duration reduces this situation.

ScrollTextIntoView() fails because flingForward() passes the text.

---

src/com/dtmilano/android/viewclient.py

- On some installations of Windows, ADB will fail to start when the
SYSTEMROOT environment variable is not present. Since it is possible
that other environment variables are required on different systems,
rather than passing an environment containing only SYSTEMROOT, a copy of
the environment with ANDROID_SERIAL removed is now being passed.

Fixing Dump on Windows 10 when adb is used to fetch the serial

---

src/com/dtmilano/android/adb/adbclient.py

Otherwise, _AndroidViewClient_ cannot figure out the display information by using `wm size; wm density`.

Fixed empty regex group for physical display info

---

src/com/dtmilano/android/viewclient.py

Hi,
My problem was when I needed to use culebra on a remote device mapped by a domain name.
Example:
$ adb devices
List of devices attached
devices.alexandre.com:7777  device
I was getting this error below, but domain name is not a regular expression.
Traceback (most recent call last):
File "single_country_wizard_multi_vertical.py", line 33, in <module>
vc = ViewClient(device, device_id, **kwargs2)
File "/home/alexandre/IdeaProjects/AndroidViewClient/src/com/dtmilano/android/viewclient.py", line 2421, in __init__
self.serialno = self.__mapSerialNo(serialno)
File "/home/alexandre/IdeaProjects/AndroidViewClient/src/com/dtmilano/android/viewclient.py", line 2609, in __mapSerialNo
raise ValueError("Regular expression not supported as serialno in ViewClient. Found '%s'" % serialno)
ValueError: …

Fixed domain name recognition

---

src/com/dtmilano/android/adb/adbclient.py

Add lock to protect the API AdbClient.shell() from being called by multiple threads simultaneously

---

src/com/dtmilano/android/adb/adbclient.py

Ran basic usage `dump` and `dump -F` against API23 AVD, both appeared to work fine.

Support Android Debug Bridge version 1.0.40

---

src/com/dtmilano/android/viewclient.py

I was having the same problem as https://github.com/dtmilano/AndroidViewClient/issues/208 and decided to track it down.
I'm running `adb` inside a Docker container on a Raspberry Pi. With the help of some of the debugging steps in the linked issue (`netstat`), I realized that adb wasn't binding to 5037.
I ended up starting adb with `adb -a -P 5037 nodaemon server` to bind to all interfaces (it seems like there is a bug where `-a` doesn't make it to the daemon). My AndroidViewClient script kept getting caught on the line changed in this PR. I believe it's because going though `AdbClient.shell` allows you to specifiy the `ANDROID_ADB_SERVER_HOST` (`0.0.0.0`) and port, whereas the changed line simply calls adb without any of AdbClient's properties.
So, this PR allows me to use AVC inside …

Use the existing AdbClient to force-stop culebratester

---

src/com/dtmilano/android/adb/adbclient.py

When running CulebraTestCase tests, this line in the AdbClient#shell() seems to cause deadlocks between main thread and RunTestsThread thread, as it should have either with self.lock or separate self.lock.acquire() and self.lock.release() statements, but not both.
Please, see #252 for details.

Fix for adb shell lock issue #252

---

src/com/dtmilano/android/adb/adbclient.py

AVC fails to detect activities created within inner classes, i.e `com.company.package/.Application$Activity`

add support for activities within inner classes

---

src/com/dtmilano/android/adb/adbclient.py

For instance matching by devpath (like usb:1.1) is very useful for
devices that have identical serial numbers.
Adb accepts
adb -s <serialno>
adb -s <devpath>
adb -s <model:name>
adb -s <device:name>
adb -t <transport_id>
Let's support first four forms the same way.
The fifth seems to work as well with serial in form 'transport_id:1'
References
append_transport, acquire_one_transport, atransport::MatchesTarget
https://android.googlesource.com/platform/system/core/+/master/adb/transport.cpp

match device by qualifiers too like adb does

---

src/com/dtmilano/android/adb/adbclient.py

Normally we match the device using serialno regexp, fetch the real
serialno and set it as a host:transport:
In case we match the device using qualifiers we can either fetch
the serialno or keep qualifier as host:transport: value, let's
switch to using qualifier to have means (devpath/usbpath qualifier)
to address devices having coinciding serialno (reflashed devices).
Without this fix we matched by devpath, picked up serialno and
got error from adb upon trying to set transport by serialno
(multiple devices error).

Keep adbclient.serialno intact if it's a valid transport name.

---

src/com/dtmilano/android/adb/adbclient.py

In adbclient.py, isScreenOn() checks for mScreenFullyOn, which was removed in API 29. Following [documentation for PowerManager](https://developer.android.com/reference/android/os/PowerManager#isScreenOn()), I added a check for interactiveState prior to the RuntimeError to enable execution on Android 10 devices. 
Another option I explored was [using screenState](https://github.com/dtmilano/AndroidViewClient/commit/32de7dad270faef4523313adda829bd81f40fe49), but the documentation seems to indicate that interactiveState should be used.

Android10 compatibility - isScreenOn

---

src/com/dtmilano/android/adb/adbclient.py

This fix adds Android 10 compatibility for ctrl+A (Generates a startActivity()) so that the top activity package is inserted in the generated code, rather than the launcher.

Generate startActivity() Android10 compatibility

---

src/com/dtmilano/android/culebron.py

Manually setting the TK window geometry when the orientation changes was causing display issues, resulting in failure to extend the window horizontally and the window taking up extra space. 
This fix removes manual geometry setting and allows the window manager to compute the correct window size based off the size of the menu bar and canvas, which in turn bases its size off of the scaled screenshot.

Window resize fix (for orientation changes)

---

src/com/dtmilano/android/viewclient.py

My script uses `AndroidViewClient` but cannot create a `ViewClient`
```python3
from com.dtmilano.android.viewclient import ViewClient
def createViewClient():
return ViewClient(*ViewClient.connectToDeviceOrExit(serialno='.*'))
vc = createViewClient()
```
The script returns the following stack trace:
```sh
File "/home/bob/workspace/script.py", line 4, in createViewClient
return ViewClient(*ViewClient.connectToDeviceOrExit(serialno='.*'))
File "/home/bob/.local/lib/python3.6/site-packages/com/dtmilano/android/viewclient.py", line 2690, in __init__
self.dump()
File "/home/bob/.local/lib/python3.6/site-packages/com/dtmilano/android/viewclient.py", line 3522, in dump
self.setViewsFromUiAutomatorDump(received)
File "/home/bob/.local/lib/python3.6/site-packages/com/dtmilano/android/viewclient.py", …
```

Fix XML parsing error when using MIUI 12 on Pocophone X3 #283

---

src/com/dtmilano/android/viewclient.py

This PR adds a `ViewClient.uninstallPackage` function. As there is already a `ViewClient.installPackage` function, the symmetric would save the user the burden of remembering the syntax and to pass the expected serial argument of `adb`.

Add a convenience function to uninstall a package via ViewClient.

---

src/com/dtmilano/android/viewclient.py

`adb install` accepts a `-g` option to grant all permissions to the installed application. This greatly help testing as it allows to skip the permission request dialogs to have a "normal" workflow of the app. This PR adds an option to `ViewClient.installPackage` to enable this feature.

Add an option to grant all permissions when installing an APK.

---

src/com/dtmilano/android/viewclient.py

The host and port were previously the default ones computed in adbclient by
reading the `ANDROID_ADB_SERVER_HOST` and `ANDROID_ADB_SERVER_PORT` environment
variables. Client code could customize the connection by setting the `connect()`
function via the eponymous argument but then the `AdbClient.hostname` and
`AdbClient.port` properties would be out of sync.
So the only way to use another host/post was to have the environment variables
defined, which meant to set `os.environ` before importing the `ViewClient` package
when these values must be set programmatically.

Add parameters to set the ADB server socket via viewclient.connectToDeviceOrExit()

---

src/com/dtmilano/android/adb/adbclient.py
src/com/dtmilano/android/viewclient.py

closes https://github.com/dtmilano/AndroidViewClient/issues/328

add 'r' in front of some regex strings.

---

src/com/dtmilano/android/viewclient.py

`match` method try to match only from the start of the string
`search` method try to match from anywhere on the string
in my specific use case, word boundary (`\b`) doesn't work with `match` if the sub-string I looking for is in the middle of the string
```
>>> import re
>>> r = re.compile(rf"\babc\b")
>>> r.match("xxx abc yyy")  # doesn't work
>>> r.search("xxx abc yyy")  # work
<re.Match object; span=(4, 7), match='abc'>
```
[a workaround can be found here](https://github.com/dtmilano/AndroidViewClient/issues/330) (`r = re.compile(fr"^.*\babc\b.*$")`) but word boundary alone should work too
#
fixes #330

refactor: use `search` instead of `match` to look for attr that match
